# services:
#   write-and-do_app_prod:
#     container_name: write-and-do_app_prod
#     build:
#       context: .
#       target: prod
#     ports:
#       - 81:81
#     volumes:
#       - .:/write-and-do
#     # env_file:
#     #   - .env.prod
#     environment:
#       NODE_ENV: production
#     restart: always
